version: '3.8'

services:
    dev:
        container_name: Health-Monitor-API_Container
        image: health-monitor-api_image:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/app/node_modules
        restart: unless-stopped

volumes:
  Health-Monitor-Api_Volume:

networks:
    nesjs-network: