@startuml
actor C.L as CL
participant AuthenticationAPI as Auth
participant DatabaseHandler as DB

title CU2: Security - Lock Computer

loop 5 times
CL -> Auth: login(username:String, password:String)
Auth -> DB: isPasswordAndUsernameValid(username:String, password:String)
DB --> Auth: false
Auth --> CL: error message
end
Auth -> CL: accessTimeout(timeoutIp:String)
@enduml